language: go
go:
  - 1.19.x
os:
  - linux
  - osx
script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.0
  - golangci-lint run
  - go vet ./...
  - go test ./...
